language: cpp

# Test matrix (TODO: add clang)
matrix:
  include:
    # Test GCC 5 with C++14
    env: GCC_VERSION=5 CPP=14 LIBCXX=Off
    os: linux
    addons: &gcc5
      apt:
        packages:
          - g++-5
          - gcc-5
        sources:
          - ubuntu-toolchain-r-test

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - which $CXX
  - which $CC

install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-timer-dev libboost-chrono-dev libboost-system-dev libboost-test-dev

before_script: cmake -D CMAKE_CXX_COMPILER=g++-5 .

script: make && make test
