language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev

before_script: cmake .

script: make && make test

notifications:
  email:
    recipients: janoma@gmail.com
    on_success: change
    on_failure: always
